#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(FLUIDSSIMULATIONPHYSICSENGINE_LIB)
#  define FLUIDSSIMULATIONPHYSICSENGINE_EXPORT Q_DECL_EXPORT
# else
#  define FLUIDSSIMULATIONPHYSICSENGINE_EXPORT Q_DECL_IMPORT
# endif
#else
# define FLUIDSSIMULATIONPHYSICSENGINE_EXPORT
#endif
